### ISSUE TITLE
Master checklist

### ISSUE THREAD

**Issue by JamesKoenig** [JamesKoenig/FieldLily#142]
- [ ] fully working user auth
  - [ ] working demo login
  - [ ] working user login
  - [ ] working user signup
  - [ ] auth errors are rendered
    - [ ] errors are cleared when switching from login to sign-up and vice versa
  - [ ] input fields are styled
  - [ ] interaction doesn't look buggy
  - [ ] buttons are styled
  - [ ] session forms adequately direct user attention away from other items in the page
  
- [ ] fully working user 'habits'
  - [ ] habits render in an index
  - [ ] habit index is styled well
  - [ ] users can create a new habit
    - [ ] errors are rendered in creation form and are cleared when switching
  - [ ] show component with associated resource information
  - [ ] owners of a habit can 
    - [ ] add resources, 
      - [ ] errors when adding resources are displayed to the user and are cleared before accessing any similar form
  - [ ] update a habit's information, or 
     - [ ] errors when updating information are displayed to the user and cleared when navigating around
  - [ ] delete a habit
     - [ ] errors when deleting or attempting to delete are displayed to the user and cleared when navigating around

- [ ] fully working habit 'resources'
  - [ ] resources render in an index
  - [ ] resource index is styled consistently with the rest of the site, especially the way habits are
  - [ ] show  component or page with a link to the habit it belongs to
  - [ ] owners of the habit a resource is associated with can:
    - [ ] update a resource
    - [ ] delete a resource
    
    
 - [ ] modal forms should close or fade out consistently
   - [ ] when a user clicks out, presses escape, or otherwise closes the modal manually
   - [ ] when a user successfully completes a task with the modal

**Comment by JamesKoenig** [comment]
This checklist doesn't currently have any reference to the user profile, which although it currently exists to the same extent that it did the first week we worked on the project (id est the styling is either nonexistent or buggy), and seems to mechanically function (to display a user's habits) in #150 (specifically in commit: https://github.com/JamesKoenig/FieldLily/tree/eb1c8505a1eaea251717ca02eda51d0ce5fb732f)

getting it back to working as it does there was literally a word change hence having even taken that action in the first place.
