### ISSUE TITLE
MVP 3 Checklist

### ISSUE THREAD

**Issue by JamesKoenig** [JamesKoenig/FieldLily#26]
# Resources
resources are tied to (think 'belong to') habits
## API:
- [x] users can create new resources
  - [x] only owners of a habit can post resources to it
- [x] resources can be rendered regardless of auth status
- [x] users can update their resources
  - [x] only the owners of a habit can update its resources
- [x] users can delete their resources
  - [x] only the owners of a habit can delete its resources
- [x]  resources should be able to be indexed globally & by habit

## Frontend:
WIP
