### ISSUE TITLE
MVP 1 checklist:

### ISSUE THREAD

**Issue by JamesKoenig** [JamesKoenig/FieldLily#7]
# Getting airborne:
- [x] Heroku is set up to use the appropriate mongoDB
- [x] Heroku hosts the site appropriately

# Basic functionality:
- [x] working auth
  - [x] auth api
  - [x] users can login
  - [x] users can sign up
  - [x] errors are displayed on login/signup forms when validations fail
  - [x] users can log out

# landing object
- [x] habit or habit-like object that displays some ``Resources`` associated with it
    - this might be tricky

**Comment by JamesKoenig** [comment]
Users cannot currently log in or sign up due to #15

Please only check this off based on the behavior of the [live deployment](https://fieldlily.herokuapp.com/#/)
